---
- hosts: amazon
  become: yes
  roles:
   - lamp-amazonlinux
  vars_files:
    - wp-vars.yml
  tasks:
    - name: 'wordpress -  Download to /tmp/wordpress.tar.gz'
      get_url:
        url: "{{ wp_url }}"
        dest: /tmp/wordpress.tar.gz 

    - name: 'wordpress - Extracting /tmp/wordpress.tar.gz'
      unarchive:
        src: /tmp/wordpress.tar.gz  
        dest: /tmp/
        remote_src: yes

    - name: 'wordpress - Deploying'
      shell: 'cp -R /tmp/wordpress/*  /var/www/html/{{domain}}/'
      
    - name: 'wordpress - Creating Wp-Config.php'
      template:
        src: ./wp-config.j2
        dest: '/var/www/html/{{domain}}/wp-config.php'

    - name: 'wordpress - Clean-Up'
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/wordpress
        - /tmp/wordpress.tar.gz
