---
- name: 'httpd - Installation '
  yum:
    name:
      - httpd
      - php
      - php-mysql
      - php-soap
      - php-mbstring
      - MySQL-python
    state: present
  notify: 'restart-httpd'


- name: 'httpd - Virtualhost Creation '
  template:
    src: virtualhost.j2
    dest: "/etc/httpd/conf.d/{{domain}}.conf"
  notify: 'restart-httpd'

- name: 'httpd - DocumentRoot Creation '
  file:
    path: "/var/www/html/{{domain}}"
    state: directory
  notify: 'restart-httpd'

- name: 'httpd - Index Page Creation '
  copy:
    src: index.html
    dest: '/var/www/html/{{domain}}'
  notify: 'restart-httpd'
